In [1]:
import sys
sys.path.append('../')

In [2]:
%load_ext autoreload
%autoreload 2

In [4]:
import torch
import math
import pandas as pd

from src.config.paths import BILINGUAL_PATH
from src.core.speech import BiASR

In [5]:
df = pd.read_parquet(BILINGUAL_PATH / 'libri-train.parquet')

In [6]:
asr = BiASR()
asr.model.print_params()

CTC Network	 7.95M  	(30.33MB) 
Conformer	 20.42M  	(77.88MB) 
Prediction Net	 4.53M  	(17.29MB) 
Link Network	 10.90M  	(41.59MB) 
Joint Network	 0.84M  	(3.21MB) 
--------------------------------------------------
Total		 44.64M  	(170.31MB) 


In [7]:
asr.train_single(df, 32, 1)

tensor([[[ -4.1070,  -0.2034,  -0.8551,  ...,  -0.0000,  -4.0328,  -1.3394],
         [ -6.6511,   0.0845,   0.1462,  ...,  -1.7025,  -6.6197,  -1.0566],
         [ -6.4974,   0.1289,   1.6443,  ...,  -2.4575,  -4.6898,  -0.0000],
         ...,
         [  0.1008,   0.1176,   0.0187,  ...,   0.0337,   0.0326,  -0.0717],
         [  0.1008,   0.1176,   0.0000,  ...,   0.0337,   0.0000,  -0.0717],
         [  0.1008,   0.0000,   0.0187,  ...,   0.0337,   0.0326,  -0.0717]],

        [[ -8.5623,  -1.9237,  -0.0673,  ...,  -0.2192,  -5.7926,  -1.6146],
         [ -8.9744,  -1.5361,  -0.3542,  ...,  -0.4656,  -5.1145,  -1.8465],
         [ -0.0000,  -0.3925,   0.2352,  ...,  -1.1225,  -6.4464,  -3.5001],
         ...,
         [  0.1008,   0.1176,   0.0187,  ...,   0.0337,   0.0326,  -0.0717],
         [  0.1008,   0.1176,   0.0187,  ...,   0.0337,   0.0326,  -0.0717],
         [  0.1008,   0.1176,   0.0187,  ...,   0.0000,   0.0326,  -0.0717]],

        [[-10.0066,  -4.6055,   2.3182,  ...

In [8]:
T = 500
d_model = 256
U = torch.zeros(T, d_model, dtype=torch.float32)

for pos in range(T):
    for i in range(d_model // 2):
        U[pos][2*i] = math.sin(pos / 10_000**(2*i / d_model))
        U[pos][2*i + 1] = math.cos(pos / 10_000**(2*i / d_model))

U_neg = U.clone()
U_neg[:, ::2] *= -1

R = torch.cat([U_neg[1:].flip(0), U], dim=0)
R.shape

torch.Size([999, 256])

In [9]:
R[T+1]

tensor([ 9.0930e-01, -4.1615e-01,  9.5814e-01, -2.8629e-01,  9.8705e-01,
        -1.6044e-01,  9.9916e-01, -4.0877e-02,  9.9748e-01,  7.0948e-02,
         9.8470e-01,  1.7424e-01,  9.6323e-01,  2.6869e-01,  9.3512e-01,
         3.5434e-01,  9.0213e-01,  4.3146e-01,  8.6573e-01,  5.0052e-01,
         8.2710e-01,  5.6205e-01,  7.8724e-01,  6.1665e-01,  7.4690e-01,
         6.6493e-01,  7.0671e-01,  7.0750e-01,  6.6713e-01,  7.4494e-01,
         6.2851e-01,  7.7780e-01,  5.9113e-01,  8.0658e-01,  5.5515e-01,
         8.3175e-01,  5.2071e-01,  8.5373e-01,  4.8788e-01,  8.7291e-01,
         4.5669e-01,  8.8962e-01,  4.2716e-01,  9.0418e-01,  3.9926e-01,
         9.1684e-01,  3.7295e-01,  9.2785e-01,  3.4821e-01,  9.3742e-01,
         3.2495e-01,  9.4573e-01,  3.0314e-01,  9.5295e-01,  2.8269e-01,
         9.5921e-01,  2.6355e-01,  9.6464e-01,  2.4565e-01,  9.6936e-01,
         2.2891e-01,  9.7345e-01,  2.1327e-01,  9.7699e-01,  1.9867e-01,
         9.8007e-01,  1.8504e-01,  9.8273e-01,  1.7

In [58]:
from src.core.speech.model.conformer.mhsa import RSPE

In [ ]:
enc = RSPE()

In [44]:
enc.fetch(5)[4]

tensor([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 

In [56]:
test = torch.arange(0,4)

In [57]:
(test[:, None ] - test[None, :])

tensor([[ 0, -1, -2, -3],
        [ 1,  0, -1, -2],
        [ 2,  1,  0, -1],
        [ 3,  2,  1,  0]])